<?php

namespace AppBundle\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSaleSummaryByCustomer($from, $to)
    {
        $sql = "SELECT c.customer_id, c.gender, c.firstname, c.lastname, MAX(sale.sale_date) as latest, COUNT(sale.sale_id) as length, SUM(sale.sale_amount) as total
            FROM customer c
            JOIN (SELECT * FROM sales1 UNION SELECT * FROM sales2) AS sale ON c.customer_id = sale.customer_id
            WHERE sale.sale_date >= ? AND sale.sale_date <= ?
            GROUP BY 1;";


        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->bindValue(1, $from);
        $stmt->bindValue(2, $to);
        $stmt->execute();
        return $stmt->fetchAll();
    }

}
