<?php

namespace AppBundle\Repository;

/**
 * SalesOneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesOneRepository extends \Doctrine\ORM\EntityRepository
{
}
