<?php

namespace AppBundle\Repository;

/**
 * SalesTwoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesTwoRepository extends \Doctrine\ORM\EntityRepository
{
}
